### ISSUE TITLE
wrong reference time used to generate primary beam

### ISSUE THREAD

**Issue by johnsmorgan** [nhurleywalker/GLEAM-X-pipeline#1]
DATE-OBS in metafits is the start time of the observation. Not using the centroid time of the observation when calculating the primary beam may lead to measurable errors.

**Comment by nhurleywalker** [comment]
You wrote the code I'm using to generate the beams. If I give it the metafits file, will it correctly calculate the centroid time from DATE-OBS and EXPOSURE?

**Comment by nhurleywalker** [comment]
Still waiting for a reply for my question from October :D

**Comment by johnsmorgan** [comment]
fixed with commit 5a15f30
