### ISSUE TITLE
List or calibrators for infield calibration check is probably incomplete

### ISSUE THREAD

**Issue by tjgalvin** [nhurleywalker/GLEAM-X-pipeline#18]
I noticed that there is a check to see whether infield calibration should be performed on an obsid dataset based on the value of a `CALIBSRC` keyword in the metafits file. If we want to perform infield calibration for all obsids moving forward this list should be expanded. I found a day with `PicA` as the `CALIBSRC` calibrator, which prompted the pipeline to attempt to load a model from a path that didn't exists.

I guess we can:
- expand the list of calibrators in expression that determines with calibration method should be done
- add an option to this script to force infield calibration irrespective of the field
- check and update the location of the models that the script references

If there a use case of the checking of the `CALIBSRC` field other than that is how it was done originally?

**Comment by nhurleywalker** [comment]
There are a couple of sources still not in the sky model, and I need to fix that. Then we can remove this logic. I've assigned myself to fix this but it won't be done for a few weeks as I have a lot of deadlines at the moment.

**Comment by nhurleywalker** [comment]
Fixed with commit 26c5439adaeed884a57a848c53fb7373200c2e4f.
