### ISSUE TITLE
Change calibration source selection

### ISSUE THREAD

**Issue by nhurleywalker** [nhurleywalker/GLEAM-X-pipeline#20]
At high frequencies the set minimum flux density (--minflux=1.0) can lead to small numbers of sources being selected, which may be reducing the quality of the resulting calibration solutions. @tjgalvin made some good suggestions:
- use the 100 brightest sources
- or, use some fraction of the total apparently flux density in that region
The first has the advantages that it is simple and will always take about the same amount of time to calibrate; the second might be more accurate but slow (depending on the fraction selected).

**Comment by nhurleywalker** [comment]
From previous experience the time it takes to find a solution increases approximately linearly with the number of sources in the model. Calibrating with 1,000 sources on Magnus takes about 1.5 hours D: Calibrating with 200 sources on Magnus takes about 24 minutes. There is no visible difference in the quality of the calibration solutions produced.

Testing performed on obsid 1203937808 (ch 169) using minflux 0.1 (-> 1000 sources) and 0.3 (-> 200 sources).

**Comment by tjgalvin** [comment]
I have updated the `crop_catalogue.py` script to let us create the sky model based on the top N number of brightest sources, after the PB attenuation. The corresponding `autocal.tmpl` has also been updated to use this mode. I think this can be closed now.

**Comment by nhurleywalker** [comment]
Fixed by @tjgalvin in 3ceecbd782b224e9b012ee0e62719ac7d5087fe9.
