### ISSUE TITLE
uvflag exit statement is "not OK"

### ISSUE THREAD

**Issue by nhurleywalker** [nhurleywalker/GLEAM-X-pipeline#21]
Using the slurm dependency --afterok:<jobid> for uvflag jobs sometimes fails because of the exit statement from CASA. It would be really nice to check whether the flagging was actually performed, e.g. by adding commands to casa to produce good exit statements to the ms_flag_by_uvdist.py script (see https://gitlab.com/Sunmish/piip/-/issues/1). In the absence of this, we could just put "exit 0" at the end of this script and hope for the best?!

**Comment by tjgalvin** [comment]
Received. I would prefer it if we can remove the actual call to `casa` here that performs the flagging, and bring that bit of the operation into the `ms_flag_by_uvdist.py` that identifies the baselines to flag. If that fails then we can look at remediating the call to CASA and getting it to return an appropriate error code - or outright overruling it

**Comment by nhurleywalker** [comment]
Love it. For now I will add `exit 0` at the end of uvflag.tmpl, and in future we can port this all to python.

**Comment by tjgalvin** [comment]
I have updated the `uvflag.tmpl` script to use the updated `ms_flag_by_uvdist.py` script, which preforms the flagging internally. The external call to CASA's `flagdata` is removed. I think this can be closed now.

**Comment by nhurleywalker** [comment]
Fixed by @tjgalvin in commit b6753502791469ba38bc5444a7d75fb344d0ad43.
