### ISSUE TITLE
Sky Model is missing PicA and HerA

### ISSUE THREAD

**Issue by johnsmorgan** [nhurleywalker/GLEAM-X-pipeline#3]
Sky Model is missing PicA and HerA

**Comment by nhurleywalker** [comment]
HerA included in commit https://github.com/nhurleywalker/GLEAM-X-pipeline/commit/c56a29ba09ae5542a840f526c0de13a0e6ffd836.

**Comment by nhurleywalker** [comment]
Pic A included in commit 1e6bfc1a33db4fdf714e723a5d6d74448c2c7953.
